#!/usr/bin/env python3
"""Regenerate the managed System + One-Pager region of README.md.

Locks the order: the system diagram (readme_assets/system_diagram.mmd) is ALWAYS
immediately followed by the one-pager (examples/resilience_brief.png). Edit the
sources — never the README between the markers. Run: python readme_build.py
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
README = ROOT / "README.md"
DIAGRAM = ROOT / "readme_assets" / "system_diagram.mmd"
PNG = "examples/resilience_brief.png"
HTML = "examples/resilience_brief.html"
BEGIN, END = "<!-- BEGIN:system", "<!-- END:system -->"


def block() -> str:
    diagram = DIAGRAM.read_text().strip()
    if not (ROOT / PNG).exists():
        sys.exit(f"one-pager missing: {PNG} — cannot build README")
    return (
        f"{BEGIN}  (generated by readme_build.py — edit readme_assets/system_diagram.mmd or examples/, not here) -->\n"
        "## 🗺 System at a Glance\n\n"
        "```mermaid\n" + diagram + "\n```\n\n"
        "## 📄 One-Pager — Resilience Brief\n\n"
        "Public, illustrative: priced physical risk, nature-based-first mitigations, benefit–cost as the referee. "
        "Click through to the full pages.\n\n"
        f"[![Resilience Brief — The Economy Runs on Exposed Ground, with the Port of Mobile worked example]({PNG})]({HTML})\n"
        f"{END}"
    )


def main() -> None:
    t = README.read_text()
    if BEGIN not in t or END not in t:
        sys.exit("markers missing — add <!-- BEGIN:system --> / <!-- END:system --> to README.md")
    new_block = block()
    t = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda _m: new_block, t, count=1, flags=re.DOTALL)
    README.write_text(t)
    print("README managed region regenerated — diagram → one-pager order locked")


if __name__ == "__main__":
    main()
